<?php
/**
 * Smile PriceRequestor request form template
 *
 * @category  Smile
 * @package   Smile\PriceRequestor
 * @author    Tetiana Lebed <teleb@smile.fr>
 * @copyright 2019 Smile
 */

/** @var Magento\Framework\View\Element\Template $block */
?>
<form class="form" id="request_price_form" method="post" data-mage-init='{"validation": {}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__("Send request for product price:")) ?></span></legend>
        <div class="field required">
            <label class="label" for="name_filed"><span><?= $block->escapeHtml(__('Your name')) ?></span></label>
            <div class="control">
                <input type="text" name="name" id="name_filed" class="input-text"
                        data-validate="{ required: true, maxlength: 255 }" />
            </div>
        </div>
        <div class="field required">
            <label class="label" for="email_filed"><span><?= $block->escapeHtml(__('Your e-mail')) ?></span></label>
            <div class="control">
                <input type="text" name="email" id="email_filed" class="input-text"
                       data-validate="{ required: true, email: true }" />
            </div>
        </div>
        <div class="field required">
            <label for="comment_field" class="label"><span><?= $block->escapeHtml(__('Comment')) ?></span></label>
            <div class="control">
                <textarea name="comment" id="comment_field" data-validate="{ required: true }"></textarea>
            </div>
        </div>
    </fieldset>
</form>
